### DISCUSSION TITLE
docker-compose and mermaid diagrams

### DISCUSSION THREAD

**Discussion by ltsallas** [schemacrawler/SchemaCrawler#920] [Q&A] [answered]
Hi and thanks for creating this awesome tool!

I am able to generate a pdf export of my database with a docker compose file like this
```
  schemacrawler:
    image: schemacrawler/schemacrawler:v16.8.1
    entrypoint: ['/opt/schemacrawler/schemacrawler.sh']
    command: --info-level=standard --command=schema --sort-columns --portable-names --output-format=pdf --output-file=/docs/db-schema.pdf --url="jdbc:postgresql://demodbservice:5432/demodb" --user=dbuser --password=password
    depends_on:
      - liquibase
    volumes:
      - ./docs:/docs
```
Now I want to use the mermaid-diagrams option, I couldn't find a docker-compose example for this one. I am getting a Error: Script engine not found with the following setup. I've downloaded the mermaid script in the scripts/ folder and then I am using the volumes to have it available inside the container. Do I have to create a custom Dockerfile and place the jython-slim jar inside?https://gist.github.com/sualeh/761e808f2803bba8e6f003e3276cf6e3

```
  schemacrawler-mermaid:
    image: schemacrawler/schemacrawler:v16.8.1
    entrypoint: [ '/opt/schemacrawler/schemacrawler.sh' ]
    command: --log-level=CONFIG --info-level=standard --command=script --script-language=python --script=scripts/mermaid.py --url="jdbc:postgresql://demodbservice:5432/demodb" --user=dbuser --password=password
    depends_on:
      - liquibase
    volumes:
      - ./scripts:/home/schcrwlr/scripts
```
