### ISSUE TITLE
After converting from XML to YAML format one linter table-exclusion-pattern does not work anymore

### ISSUE THREAD

**Issue by ThisGuenter** [schemacrawler/SchemaCrawler#419]
# Bug Report

**Issue**

```yaml
  - id: schemacrawler.tools.linter.LinterTableWithPrimaryKeyNotFirst
    run: true
    severity: high
    table-exclusion-pattern: .*\.(^[A-Z]{2,5}_DWH_)
```

Please explain the issue briefly
I want to exlude all tables which starts with 2-5 alphabetical characters and continue with "\_DWH\_", in the old XML-format the
table-exclusion-pattern worked:
```javascript
<table-exclusion-pattern><![CDATA[.*\.(^[A-Z]{2,5}_DWH_)]]></table-exclusion-pattern>
```

**Environment**

Specify the
* version of SchemaCrawler that you are using: 16.12.3
* version of Java that you are using:  1.8.0_172-b11
* operating system and version that you are using: Windows 10 64-bit
* relational database and version that you are using: ORACLE 12c
* JDBC driver and version that you are using: 19.7.0.0

>
